### ISSUE TITLE
Are multiple flags supported?

### ISSUE THREAD

**Issue by tejasmanohar** [ogier/pflag#26]
Does this library support passing multiple flags of the same key?

e.g. --something=... --something=... --something=...
parsed to [...,...,...]

**Comment by ogier** [comment]
Not explicitly. You can support this by writing something that satisfies the [Value interface](https://godoc.org/github.com/ogier/pflag#Value) and updates a slice when Set is called instead of overwriting the value.

spf13 has a fork at spf13/pflag with StringArray and a StringSlice flags which do something similar.
