### ISSUE TITLE
Why create this project?

### ISSUE THREAD

**Issue by anticpp** [ogier/pflag#30]
Well..what's different from standard library?

**Comment by ogier** [comment]
The standard library's flag package only parses flags with a single dash as in `-flag=value`. I believe this is due to the Go language authors' history with the Plan9 operating system. Modern command line utilities on Linux typically follow the GNU/Posix standards for flags which use double dashes `--flag=value` with an optional `=` sign, and often accept shorthands for flags with a single dash `-r -f` which can be combined for brevity `-rf`. This package implements this way of parsing flags so that you can write command line utilities with a modern look and feel.
